---
# tasks file for sshd

- name: Install sshd
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ sshd_packages }}"
    - "{{ sshd_additional_packages }}"
  tags:
    - package
    - sshd

- name: Create Folder for privilege separation
  file:
    path: /var/run/sshd
    owner: root
    group: root
    mode: 0750
    state: directory
  tags:
    - setup
    - sshd

- name: Set config
  template:
    src: "{{ item }}"
    dest: "/etc/ssh/{{ item | basename |  replace('.j2', '') }}"
    owner: root
    group: root
    mode: 0644
    validate: "/usr/sbin/sshd -t -f %s"
  notify: reload sshd
  with_items:
    - "{{ sshd_config_file }}"
  tags:
    - config
    - sshd

- name: Enable service
  service:
    name: ssh
    enabled: yes
    state: started
  tags:
    - service
    - sshd
