---

- name: reload sshd
  service:
    name: ssh
    state: reloaded

- name: restart sshd
  service:
    name: ssh
    state: restarted

- name: start sshd
  service:
    name: ssh
    state: started

- name: stop sshd
  service:
    name: ssh
    state: stopped
